// Opt-in: synthetic FRC02 BrowserServer8092 + workspace Next3111 and isolated PostgreSQL.
const {chromium}=require('../../node_modules/@playwright/test');
const fs=require('node:fs');const assert=require('node:assert/strict');const crypto=require('node:crypto');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.FRC05_BROWSER_BASE_URL||'http://127.0.0.1:3111';const out='/private/tmp/fortis-frc05-browser';fs.mkdirSync(out,{recursive:true});
try {
const fixture=await (await fetch('http://127.0.0.1:8092/__fixture')).json();
await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill('B@example.test');await page.getByLabel('Password',{exact:true}).fill('fixture-password-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/workspace');
const project=JSON.parse(fs.readFileSync('test/fixtures/frc04-project.json','utf8'));const finance=JSON.parse(fs.readFileSync('test/fixtures/finance-v1.json','utf8'));
project.baseObject.id=fixture.b.enterpriseId;project.projectName='Synthetic FRC05 costing';
project.layers=finance.layers.map((layer,i)=>({...project.layers[1],...layer,order:i,isVisible:true,isLocked:false}));
project.assetLibrary=finance.assets.map(asset=>({...project.assetLibrary[0],...asset,category:'software',roles:['monitor'],currency:'RUB',unitPriceMinor:asset.unitPriceMinor,pricePerUnitMln:Number(asset.unitPriceMinor)/100000000}));
project.placedObjects=finance.variantA.objects.map(object=>{const result={...project.placedObjects[0],...object,name:object.id};delete result.customPricePerUnitMln;delete result.customPriceMinor;if(object.customPriceMinor!==undefined)result.customPriceMinor=object.customPriceMinor;return result;});
const created=await page.request.post(base+'/api/defense/projects',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{name:project.projectName,enterpriseId:fixture.b.enterpriseId,projectJson:JSON.stringify(project)}});assert.equal(created.status(),200,await created.text());const summary=await created.json();const id=summary.projectId??summary.id;assert.ok(id,JSON.stringify(summary));
const response=await page.request.get(base+'/api/v1/projects/cost?projectId='+id+'&projectVersion=1');assert.equal(response.status(),200,await response.text());const cost=await response.json();assert.equal(cost.totalMinor,'47500000');assert.deepEqual(cost.byLayer.map(x=>x.totalMinor),['25000000','22500000']);assert.equal(cost.identity.projectVersion,1);
await page.goto(base+'/prototype?projectId='+id);await page.getByText("Смета сохранённой версии 1",{exact:true}).waitFor({timeout:60000});await page.getByTitle('Просчитать конфигурацию в калькуляторе').click();await page.getByRole('heading',{name:'Стоимость конфигурации',exact:true}).waitFor();await page.getByText('Сохранённая версия 1',{exact:true}).waitFor();assert.equal(await page.locator('h2').innerText(),'475 000,00 ₽');assert.equal(await page.getByText('3 позиций · 6 единиц',{exact:true}).count(),1);assert.equal(await page.getByRole('heading',{name:'obj-2',exact:true}).count(),1);
for(const width of [1440,375]){await page.setViewportSize({width,height:960});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:out+'/saved-cost-'+width+'.png',fullPage:true});}
const again=await page.request.get(base+'/api/v1/projects/cost?projectId='+id+'&projectVersion=1');assert.deepEqual(await again.json(),cost);assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',projectId:id,version:1,totalMinor:cost.totalMinor,groups:cost.byLayer.map(x=>x.totalMinor),hiddenObjectIncluded:true,widths:[1440,375],pageErrors:errors,screenshots:out}));
}catch(error){await page.screenshot({path:out+"/failure.png",fullPage:true});fs.writeFileSync(out+"/failure.txt",await page.locator("body").innerText());throw error;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
