// Synthetic BrowserServer8092 uses real PostgreSQL/private local files and a test-only clean scanner.
const {chromium}=require('../../node_modules/@playwright/test');const fs=require('node:fs');const assert=require('node:assert/strict');const crypto=require('node:crypto');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:960},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:3111';const out='/private/tmp/fortis-frc09-browser';fs.mkdirSync(out,{recursive:true});try{
const fixture=await(await fetch('http://127.0.0.1:8092/__fixture')).json();
await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill('B@example.test');await page.getByLabel('Password',{exact:true}).fill('fixture-password-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/workspace');
const payload={name:'Synthetic <b>source</b>',description:'Text <script>alert(1)</script>',category:'software',roles:['monitor'],coverageType:'none',currency:'RUB',unitLabel:'шт',pricePerUnitMln:0.125,unitPriceMinor:'12500000',isPublic:false,enterpriseId:fixture.b.enterpriseId,provenance:null};
const created=await page.request.post(base+'/api/v1/assets',{data:payload});assert.equal(created.status(),201,await created.text());const asset=await created.json();
const project={schemaVersion:1,projectName:'Synthetic document workspace',baseObject:{id:fixture.b.enterpriseId,name:'Synthetic object',center:{lat:0,lng:0}},layers:[],assetLibrary:[{...payload,id:asset.id,provenance:null,placementType:'non-physical',deploymentType:'software',tags:[],mapCatalogGroupIds:[],recommendedLayerCodes:[]}],placedObjects:[],mode:'edit'};
const saved=await page.request.post(base+'/api/defense/projects',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{name:project.projectName,enterpriseId:fixture.b.enterpriseId,projectJson:JSON.stringify(project)}});assert.equal(saved.status(),200,await saved.text());const summary=await saved.json();
await page.goto(base+'/prototype?projectId='+summary.projectId);await page.getByLabel('Редактировать выбранное средство',{exact:true}).click();const panel=page.getByRole('region',{name:'Документы карточки',exact:true});await panel.getByText('Документы пока не загружены.',{exact:true}).waitFor();
await panel.getByLabel('Файл документа').setInputFiles({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('Not a PDF')});await panel.getByRole('button',{name:'Загрузить файл',exact:true}).click();await panel.getByText(/Содержимое файла не соответствует/).waitFor();
const bytes=Buffer.from('Synthetic source document\nNo customer data.\n');await panel.getByLabel('Файл документа').setInputFiles({name:'source.txt',mimeType:'text/plain',buffer:bytes});const uploadResponse=page.waitForResponse(r=>r.url().endsWith('/api/v1/assets/documents')&&r.request().method()==='POST');await panel.getByRole('button',{name:'Загрузить файл',exact:true}).click();const uploaded=await uploadResponse;assert.equal(uploaded.status(),201,await uploaded.text());const document=await uploaded.json();assert.equal(document.checksum,crypto.createHash('sha256').update(bytes).digest('hex'));await panel.getByText('Готов к скачиванию',{exact:true}).waitFor();
const pendingDownload=page.waitForEvent('download');await panel.getByRole('button',{name:'Скачать',exact:true}).click();const download=await pendingDownload;assert.deepEqual(fs.readFileSync(await download.path()),bytes);assert.equal(download.suggestedFilename(),'source.txt');
await panel.getByRole('button',{name:'Использовать как источник',exact:true}).click();assert.equal(await page.getByLabel('Качество данных',{exact:true}).inputValue(),'estimated');const [updated]=await Promise.all([page.waitForResponse(r=>r.url().includes('/api/v1/assets/update')&&r.request().method()==='PUT'),page.getByRole('button',{name:'save Сохранить',exact:true}).click()]);assert.equal(updated.status(),200,await updated.text());const updatedAsset=await updated.json();assert.equal(updatedAsset.provenance.sourceDocumentId,document.id);assert.equal(updatedAsset.provenance.sourceDocumentRevision,document.revision);assert.equal(updatedAsset.provenance.sourceDocumentChecksum,document.checksum);await page.getByRole('button',{name:'Применить к черновику',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:out+'/source-preview.png',fullPage:true});await page.getByRole('button',{name:'Применить к черновику',exact:true}).click();await page.getByText('Черновая смета — изменения не сохранены',{exact:true}).waitFor();assert.equal(await page.locator('script').filter({hasText:'alert(1)'}).count(),0);
// Another authenticated tenant cannot retrieve the same immutable document.
const other=await browser.newContext();const a=await other.newPage();await a.goto(base+'/login');await a.getByLabel('Email',{exact:true}).fill('A@example.test');await a.getByLabel('Password',{exact:true}).fill('fixture-password-only');await a.getByRole('button',{name:'Sign in',exact:true}).click();await a.waitForURL('**/workspace');const denied=await a.request.get(base+'/api/v1/assets/documents/download?id='+document.id);assert.equal(denied.status(),404);await other.close();
const before=await page.request.get(base+'/api/v1/assets/documents/list?assetId='+asset.id);assert.equal((await before.json()).totalItems,1);await panel.getByRole('button',{name:'Удалить документ',exact:true}).click();await panel.getByText('Документы пока не загружены.',{exact:true}).waitFor();const deleted=await page.request.get(base+'/api/v1/assets/documents/download?id='+document.id);assert.equal(deleted.status(),404);assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',projectId:summary.projectId,documentId:document.id,revision:document.revision,checksum:document.checksum,invalidMime:415,foreignDownload:404,deletedDownload:404,realPrivateStorage:true,scanner:'test-only',pageErrors:errors,screenshot:out+'/source-preview.png'}));
}catch(e){await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.txt',await page.locator('body').innerText());throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
