// Opt-in local release check; start the documented frontend/backend fixtures first.
const {chromium}=require("../../node_modules/@playwright/test");
const assert=require("node:assert/strict");const fs=require("node:fs");
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const base='http://127.0.0.1:3111';const out='/private/tmp/fortis-frc11-browser';fs.mkdirSync(out,{recursive:true});
try {for(const width of [375,414,768,1024,1280,1440]) {await page.setViewportSize({width,height:width===1280?720:width===1440?960:900});await page.goto(base);await page.getByRole('heading',{name:'Планирование конфигураций и бюджета безопасности объекта',exact:true}).waitFor();assert.match(await page.title(),/Fortis/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'overflow '+width);assert.equal(await page.locator('nextjs-portal').getByText(/Runtime Error|Build Error/).count(),0);for(let y=0;y<await page.evaluate(()=>document.documentElement.scrollHeight);y+=600){await page.evaluate(y=>scrollTo(0,y),y);await page.waitForTimeout(700);}await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(700);await page.screenshot({path:out+'/landing-'+width+'.png',fullPage:true});}
await page.getByRole('link',{name:'Запросить демонстрацию',exact:true}).first().click();await page.waitForURL('**/#cta');await page.getByText(/Приём заявок сейчас недоступен|не создаёт заявку|Форма приёма заявок/).first().waitFor();
for (const path of ['/dashboard','/dashboard/alert','/dashboard/incidents','/dashboard/reports','/dashboard/settings','/dashboard/sites','/dashboard/sites/anything','/dashboard/team','/retrospective-analysis']) {await page.goto(base+path);await page.getByText('Раздел не включён в текущий рабочий релиз.',{exact:true}).waitFor();assert.equal(await page.getByText('Демонстрационные данные',{exact:true}).count(),0);}
await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill('B@example.test');await page.getByLabel('Password',{exact:true}).fill('fixture-password-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/workspace');await page.getByRole('button',{name:'Enterprise B',exact:true}).waitFor();
for(const path of ['/prototype?view=scenario-modeling','/prototype?view=3d']) {await page.goto(base+path);await page.getByText('Раздел не включён в текущий рабочий релиз.',{exact:true}).waitFor();}
await page.screenshot({path:out+'/workspace-notice.png',fullPage:true});assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',widths:[375,414,768,1024,1280,1440],blockedDirectRoutes:11,consoleErrors:errors,screenshots:out}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
